import type { JSX } from 'react'
import {
    BiBarChartAlt, BiBookBookmark, BiBookOpen,
    BiBookReader, BiCodeAlt,
    BiCodeBlock, BiCodeCurly, BiCommand, BiCubeAlt, BiDetail, BiDownload, BiFileBlank, BiGridAlt, BiHome, BiInfoCircle, BiLayer, BiPlusCircle, BiQuestionMark, BiShieldAlt2, BiSitemap, BiSolidHand, BiTask, BiTestTube
} from 'react-icons/bi'
import { BsInfoCircle } from 'react-icons/bs'
import { CiVault } from 'react-icons/ci'
import { GiRadarSweep } from 'react-icons/gi'
import { GoLaw } from 'react-icons/go'
import { GrGroup, GrValidate } from 'react-icons/gr'
import { HiOutlineBuildingLibrary } from 'react-icons/hi2'
import { LuMonitor } from 'react-icons/lu'
import {
    PiBoneDuotone,
    PiBookDuotone,
    PiBreadDuotone,
    PiBrowsersDuotone,
    PiCalendarCheckDuotone,
    PiCalendarDuotone,
    PiCardsDuotone,
    PiCaretCircleDownDuotone,
    PiChalkboardSimpleDuotone,
    PiChartBarDuotone,
    PiChartDonutDuotone,
    PiChartLineUpDuotone,
    PiChartPieSliceDuotone,
    PiChatCenteredDotsDuotone,
    PiChatCenteredDuotone,
    PiChatCircleDuotone,
    PiChatDotsDuotone,
    PiCheckSquareDuotone,
    PiCircleHalfTiltDuotone,
    PiClipboardTextDuotone,
    PiClockAfternoonDuotone,
    PiClockCountdownDuotone,
    PiCodeDuotone,
    PiCodeSimpleDuotone,
    PiCompassDuotone,
    PiCurrencyCircleDollarDuotone,
    PiCursorClickDuotone,
    PiDesktopDuotone,
    PiDotsThreeCircleDuotone,
    PiEnvelopeDuotone,
    PiFileMagnifyingGlassDuotone,
    PiFileTextDuotone,
    PiFilmScriptDuotone,
    PiFolderOpenDuotone,
    PiFootprintsDuotone,
    PiGearDuotone,
    PiGridFourDuotone,
    PiHandWithdrawDuotone,
    PiHeadsetDuotone,
    PiHouseLineDuotone,
    PiImagesDuotone,
    PiKeyDuotone,
    PiKeyholeDuotone,
    PiLightbulbDuotone,
    PiListChecksBold,
    PiListChecksDuotone,
    PiListDuotone,
    PiListMagnifyingGlassDuotone,
    PiListPlusDuotone,
    PiListStarDuotone,
    PiLockKeyOpenDuotone,
    PiMapTrifoldDuotone,
    PiMedalDuotone,
    PiMegaphoneDuotone,
    PiNewspaperDuotone,
    PiNotePencilDuotone,
    PiPackageDuotone,
    PiPasswordDuotone,
    PiPencilSimpleLineDuotone,
    PiPlusSquareDuotone,
    PiProjectorScreenChartDuotone,
    PiPuzzlePieceDuotone,
    PiQuotesDuotone,
    PiRadioButtonDuotone,
    PiRocketDuotone,
    PiRowsDuotone,
    PiRowsPlusBottomDuotone,
    PiShareNetworkDuotone,
    PiShieldCheckDuotone,
    PiShoppingCartDuotone,
    PiShoppingCartSimpleDuotone,
    PiSparkleDuotone,
    PiSpeedometerDuotone,
    PiSpinnerBallDuotone,
    PiSpinnerGapDuotone,
    PiStackPlusDuotone,
    PiSwatchesDuotone,
    PiTableDuotone,
    PiTagDuotone,
    PiTextAaDuotone,
    PiTextIndentDuotone,
    PiToggleRightDuotone,
    PiToolboxDuotone,
    PiUploadDuotone,
    PiUserCircleDuotone,
    PiUserGearDuotone,
    PiUserListDuotone,
    PiUserPlusDuotone,
    PiUsersDuotone,
    PiWarningDuotone,
} from 'react-icons/pi'
import { TbBrandAo3 } from 'react-icons/tb'
import { TfiHelpAlt } from 'react-icons/tfi'
export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    uiComponents: <PiPuzzlePieceDuotone />,
    common: <PiSwatchesDuotone />,
    uiCommonButton: <PiCursorClickDuotone />,
    uiCommonGrid: <PiGridFourDuotone />,
    uiCommonTypography: <PiTextAaDuotone />,
    uiCommonIcons: <PiImagesDuotone />,
    feedback: <PiChatDotsDuotone />,
    uiFeedbackAlert: <PiWarningDuotone />,
    uiFeedbackDialog: <PiChatCircleDuotone />,
    uiFeedbackDrawer: <PiHandWithdrawDuotone />,
    uiFeedbackProgress: <PiSpinnerGapDuotone />,
    uiFeedbackSkeleton: <PiBoneDuotone />,
    uiFeedbackSpinner: <PiSpinnerBallDuotone />,
    uiFeedbackToast: <PiBreadDuotone />,
    dataDisplay: <PiDesktopDuotone />,
    uiDataDisplayAvatar: <PiUserCircleDuotone />,
    uiDataDisplayBadge: <PiMedalDuotone />,
    uiDataDisplayCalendar: <PiCalendarDuotone />,
    uiDataDisplayCard: <PiCardsDuotone />,
    uiDataDisplayTable: <PiTableDuotone />,
    uiDataDisplayTag: <PiTagDuotone />,
    uiDataDisplayTimeline: <PiClockCountdownDuotone />,
    uiDataDisplayTooltip: <PiChatCenteredDuotone />,
    forms: <PiFileTextDuotone />,
    uiFormsCheckbox: <PiCheckSquareDuotone />,
    uiFormsDatepicker: <PiCalendarCheckDuotone />,
    uiFormsFormControl: <PiClipboardTextDuotone />,
    uiFormsInput: <PiRowsDuotone />,
    uiFormsInputGroup: <PiRowsPlusBottomDuotone />,
    uiFormsRadio: <PiRadioButtonDuotone />,
    uiFormsSegment: <PiChartDonutDuotone />,
    uiFormsSelect: <PiListChecksBold />,
    uiFormsSwitcher: <PiToggleRightDuotone />,
    uiFormsTimePicker: <PiClockAfternoonDuotone />,
    uiFormsUpload: <PiUploadDuotone />,
    navigation: <PiCompassDuotone />,
    uiNavigationDropdown: <PiCaretCircleDownDuotone />,
    uiNavigationMenu: <PiListDuotone />,
    uiNavigationPagination: <PiCodeSimpleDuotone />,
    uiNavigationSteps: <PiFootprintsDuotone />,
    uiNavigationTabs: <PiBrowsersDuotone />,
    graph: <PiChartPieSliceDuotone />,
    uiGraphChart: <PiChartLineUpDuotone />,
    uiGraphMaps: <PiMapTrifoldDuotone />,
    concepts: <PiLightbulbDuotone />,
    customers: <PiUsersDuotone />,
    customerList: <PiUserListDuotone />,
    customerEdit: <PiPencilSimpleLineDuotone />,
    customerCreate: <PiUserPlusDuotone />,
    customerDetails: <PiUserCircleDuotone />,
    products: <PiPackageDuotone />,
    productList: <PiListStarDuotone />,
    productEdit: <PiNotePencilDuotone />,
    productCreate: <PiPlusSquareDuotone />,
    projects: <PiProjectorScreenChartDuotone />,
    projectScrumBoard: <PiChalkboardSimpleDuotone />,
    projectList: <PiListChecksDuotone />,
    projectDetails: <PiFileMagnifyingGlassDuotone />,
    projectTask: <PiCalendarCheckDuotone />,
    projectIssue: <PiWarningDuotone />,
    orders: <PiShoppingCartDuotone />,
    orderList: <PiListPlusDuotone />,
    orderEdit: <PiFilmScriptDuotone />,
    ordeDetails: <PiListMagnifyingGlassDuotone />,
    orderCreate: <PiStackPlusDuotone />,
    calendar: <PiCalendarDuotone />,
    fileManager: <PiFolderOpenDuotone />,
    mail: <PiEnvelopeDuotone />,
    account: <PiUserCircleDuotone />,
    accountSettings: <PiGearDuotone />,
    accountActivityLogs: <PiFileTextDuotone />,
    accountRoleAndPermission: <PiUserGearDuotone />,
    accountPricing: <PiCurrencyCircleDollarDuotone />,
    ai: <PiSparkleDuotone />,
    aiChat: <PiChatCenteredDotsDuotone />,
    aiImage: <PiImagesDuotone />,
    chat: <PiChatCircleDuotone />,
    helpCenter: <TfiHelpAlt />,
    helpCeterSupportHub: <PiHeadsetDuotone />,
    helpCeterArticle: <PiNewspaperDuotone />,
    helpCeterEditArticle: <PiTextIndentDuotone />,
    helpCeterManageArticle: <PiQuotesDuotone />,
    authentication: <PiShieldCheckDuotone />,
    signIn: <PiKeyDuotone />,
    signUp: <PiUserPlusDuotone />,
    forgotPassword: <PiLockKeyOpenDuotone />,
    resetPassword: <PiKeyholeDuotone />,
    otpVerification: <PiPasswordDuotone />,
    dashboard: <PiSpeedometerDuotone />,
    dashboardEcommerce: <PiShoppingCartSimpleDuotone />,
    dashboardProject: <PiRocketDuotone />,
    dashboardAnalytic: <PiChartBarDuotone />,
    dashboardMarketing: <PiMegaphoneDuotone />,
    others: <PiDotsThreeCircleDuotone />,
    accessDenied: <PiCircleHalfTiltDuotone />,
    landing: <PiHouseLineDuotone />,
    documentation: <PiBookDuotone />,
    sharedComponentDoc: <PiShareNetworkDuotone />,
    utilsDoc: <PiToolboxDuotone />,
    changeLog: <PiCodeDuotone />,
    about: <BsInfoCircle />,
    law: <GoLaw />,
    vaults: <CiVault />,
    monitors: <LuMonitor />,
    validators: <GrValidate />,
    dao: <TbBrandAo3 />,
    universal: <BiFileBlank />,
    // landing: <IoHomeOutline />,
    homeicon: <BiHome />,
    vaultsicon: <BiShieldAlt2 />,
    monitorsicon: <GiRadarSweep />,
    validatorsicon: <BiTestTube />,
    daoicon: <HiOutlineBuildingLibrary />,
    legalicon: <BiShieldAlt2 />,
    documentationicon: <BiBookBookmark />,
    helpcentericon: <BiQuestionMark />,
    abouticon: <BiInfoCircle />,

    // Sub-menu items
    createicon: <BiPlusCircle />,
    statusicon: <BiTask />,
    networkicon: <BiSitemap />,
    statisticsicon: <BiBarChartAlt />,
    dashboardicon: <BiGridAlt />,
    votingicon: <BiSolidHand />,
    testsicon: <BiTestTube />,
    structureicon: <BiCubeAlt />,
    governanceicon: <GrGroup />,
    installationicon: <BiDownload />,
    protocolicon: <BiCommand />,
    privacyicon: <BiShieldAlt2 />,
    apiicon: <BiCodeAlt />,
    sdkicon: <BiCodeBlock />,
    tutorialicon: <BiBookOpen />,
    userguideicon: <BiBookReader />,
    faqicon: <BiQuestionMark />,
    examplesicon: <BiDetail />,
    usecasesicon: <BiLayer />,
    zuzdslicon: <BiCodeCurly />,
}

export default navigationIcon
